FROM nginx
COPY default.conf /etc/nginx/conf.d/default.conf
COPY account/*.html /usr/share/nginx/html/account/
COPY *.html /usr/share/nginx/html/
COPY login-register/*.html /usr/share/nginx/html/login-register/
COPY payment/*.html /usr/share/nginx/html/payment/
COPY result/*.html /usr/share/nginx/html/result/
COPY assets/css/* /usr/share/nginx/html/assets/css/
COPY assets/fonts/* /usr/share/nginx/html/assets/fonts/
COPY assets/img/* /usr/share/nginx/html/assets/img/
COPY assets/js/* /usr/share/nginx/html/assets/js/